# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: 
    git clone --mirror "https://anything:%TOKEN%@dev.azure.com/aleksej-strassheim/OpenDiabetes-plot/_git/OpenDiabetes-site"
- script: 
    cd OpenDiabetes-site
- script: 
    git remote add --mirror=fetch secondary https://%USERNAME%:%PASSWORD%@github.com/Creative332/OpenDiabetes-Plot.git
- script: 
    git fetch origin
- script: 
    git push secondary --all
